--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels: 
    name: bggapp-deploy
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      name: bggapp-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      name: bggapp-pod
      labels:
        name: bggapp-pod
    spec:
      containers:
      - name: bggapp-container
        #image: chukmunnlee/bggapp:v2
        image: amoztanpsa/bggapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels: 
    name: bggapp-svc

spec:
  type: LoadBalancer
  selector: 
    name: bggapp-pod
  ports:
  - port: 8080
    targetPort: 3000