---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-cm
  labels:
    name: wp-cm
data:
  WORDPRESS_DB_HOST: wpdb-svc.wordpressns.svc.cluster.local
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_NAME: mydb