---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: wpdb-mysql
  labels:
    name: wpdb-mysql
spec:
  replicas: 1
  secretName: wpdb-secret
  persistentVolumeClaim:
    storageClassName: do-block-storage
    accessModes:
    - ReadWriteOnce
    resources:
      request:
        storage: 1Gi
    initFileExtraSQL:
      -"Create database mydb"

---
apiVersion: networking.k8s.io/v1
kind: NetworkingPolicy
metadata:
  name: wpdb-netpol
  labels:
    name: wpdb-netpol

spec:
  podSelector:
    matchLabels:
      name: app.kubernetes.io/instance: wpdb-mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: wordpress-pod
    ports:
    - port: 3306
      protocol: TCP
