--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels: 
    name: bggapp-deploy
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      name: bggapp-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      name: bggapp-pod
      labels:
        name: bggapp-pod
    spec:
      containers:
      - name: bggapp-container
        #image: chukmunnlee/bggapp:v2
        image: amoztanpsa/bggapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels: 
    name: bggapp-svc

spec:
  type: ClusterIP
  selector: 
    name: bggapp-pod
  ports:
  - port: 8080
    targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bggapp-ing
  labels:
    name: bggapp-ing

spec:
  ingressClassName: nginx
  rules:
  - host: bggapp.144.126.242.210.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bggapp-svc
            port:
              number: 8080
